name: E2E Tests Custom

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''
      browsers:
        description: 'Comma-separated list of browsers to execute tests against (e.g., chrome,firefox,edge,safari)'
        default: 'chrome,firefox'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    outputs:
      selected: ${{ steps.process.outputs.selected }}
    steps:
      - name: Process Browser Input
        id: process
        run: |
          browsers="${{ github.event.inputs.browsers }}"
          echo "Selected browsers: $browsers"
          echo "::set-output name=selected::$browsers"

  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    needs: preprocess
    if: contains(needs.preprocess.outputs.selected, 'chrome')
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Install Allure on Linux
        run: |
          curl -o allure https://raw.githubusercontent.com/allure-framework/allure2/master/bin/allure
          chmod +x allure
          sudo mv allure /usr/local/bin/allure
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="chrome" -DexecutionAddress="local" -DtargetOperatingSystem="LINUX" -DheadlessExecution="true" -DchromeOptionsArgs="--disable-dev-shm-usage,--no-sandbox" -Dtest="${{ github.event.inputs.testsPath }}"
      - name: Generate Allure Report
        run: allure generate --single-file -o allure-report
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Allure
          path: allure-report/*

  E2E_Firefox_Linux_Test:
    runs-on: ubuntu-latest
    needs: preprocess
    if: contains(needs.preprocess.outputs.selected, 'firefox')
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Install Allure on Linux
        run: |
          curl -o allure https://raw.githubusercontent.com/allure-framework/allure2/master/bin/allure
          chmod +x allure
          sudo mv allure /usr/local/bin/allure
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="firefox" -DexecutionAddress="local" -DtargetOperatingSystem="LINUX" -DheadlessExecution="true" -Dtest="${{ github.event.inputs.testsPath }}"
      - name: Generate Allure Report
        run: allure generate --single-file -o allure-report
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Firefox_Linux_Allure
          path: allure-report/*

  E2E_Edge_Windows_Test:
    runs-on: windows-latest
    needs: preprocess
    if: contains(needs.preprocess.outputs.selected, 'edge')
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="microsoftedge" -DexecutionAddress="local" -DtargetOperatingSystem="WINDOWS" -Dtest="${{ github.event.inputs.testsPath }}"
      - name: Generate Allure Report
        run: |
          .\allure.bat generate --single-file -o allure-report
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Allure
          path: allure-report/*

  E2E_Safari_MacOS_Test:
    runs-on: macos-latest
    needs: preprocess
    if: contains(needs.preprocess.outputs.selected, 'safari')
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="safari" -DexecutionAddress="local" -DtargetOperatingSystem="MAC" -Dtest="${{ github.event.inputs.testsPath }}"
      - name: Generate Allure Report
        run: allure generate --single-file -o allure-report
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Safari_MacOS_Allure
          path: allure-report/*
